package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentCashRcd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentCashRcd extends BaseAgentCashRcd<AgentCashRcd> {
	public static final String table = "t_agent_cash_rcd";
}
