package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentCommRcd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentCommRcd extends BaseAgentCommRcd<AgentCommRcd> {
	public static final String table = "t_agent_comm_rcd";
}
