package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentCommssion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentCommssion extends BaseAgentCommssion<AgentCommssion> {
	public static final String table = "t_agent_commssion";
}
