package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseBuyerCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyerCard extends BaseBuyerCard<BuyerCard> {
	public static final String table = "t_buyer_card";
}
