package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Card extends BaseCard<Card> {
	public static final String table = "t_card";
}
