package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseCashbackRcd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CashbackRcd extends BaseCashbackRcd<CashbackRcd> {
	public static final String table = "t_cashback_rcd";
}
