package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseCashbackProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CashbackProduct extends BaseCashbackProduct<CashbackProduct> {
	public static final String table = "t_cashback_product";
}
