package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseMultiGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MultiGroup extends BaseMultiGroup<MultiGroup> {
	public static final String table = "t_multi_group";
}
