package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseMultiGroupSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MultiGroupSet extends BaseMultiGroupSet<MultiGroupSet> {
	public static final String table = "t_multi_group_set";
}
