package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAgentRank<M extends BaseAgentRank<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setRankName(java.lang.String rankName) {
		set("rank_name", rankName);
		return (M)this;
	}

	public java.lang.String getRankName() {
		return get("rank_name");
	}

	public M setFirstRate(java.math.BigDecimal firstRate) {
		set("first_rate", firstRate);
		return (M)this;
	}

	public java.math.BigDecimal getFirstRate() {
		return get("first_rate");
	}

	public M setSecondRate(java.math.BigDecimal secondRate) {
		set("second_rate", secondRate);
		return (M)this;
	}

	public java.math.BigDecimal getSecondRate() {
		return get("second_rate");
	}

	public M setThirdRate(java.math.BigDecimal thirdRate) {
		set("third_rate", thirdRate);
		return (M)this;
	}

	public java.math.BigDecimal getThirdRate() {
		return get("third_rate");
	}

	public M setRewardValue(java.lang.Integer rewardValue) {
		set("reward_value", rewardValue);
		return (M)this;
	}

	public java.lang.Integer getRewardValue() {
		return get("reward_value");
	}

	public M setGetCashTime(java.lang.Integer getCashTime) {
		set("get_cash_time", getCashTime);
		return (M)this;
	}

	public java.lang.Integer getGetCashTime() {
		return get("get_cash_time");
	}

	public M setGetCashLimit(java.lang.Integer getCashLimit) {
		set("get_cash_limit", getCashLimit);
		return (M)this;
	}

	public java.lang.Integer getGetCashLimit() {
		return get("get_cash_limit");
	}

	public M setChildrenCount(java.lang.Integer childrenCount) {
		set("children_count", childrenCount);
		return (M)this;
	}

	public java.lang.Integer getChildrenCount() {
		return get("children_count");
	}

	public M setTotalCommission(java.math.BigDecimal totalCommission) {
		set("total_commission", totalCommission);
		return (M)this;
	}

	public java.math.BigDecimal getTotalCommission() {
		return get("total_commission");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
