package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExpressTemplate<M extends BaseExpressTemplate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setExpName(java.lang.String expName) {
		set("exp_name", expName);
		return (M)this;
	}

	public java.lang.String getExpName() {
		return get("exp_name");
	}

	public M setExpKey(java.lang.String expKey) {
		set("exp_key", expKey);
		return (M)this;
	}

	public java.lang.String getExpKey() {
		return get("exp_key");
	}

	public M setExpTplcontent(java.lang.String expTplcontent) {
		set("exp_tplcontent", expTplcontent);
		return (M)this;
	}

	public java.lang.String getExpTplcontent() {
		return get("exp_tplcontent");
	}

	public M setExpDesignhtml(java.lang.String expDesignhtml) {
		set("exp_designhtml", expDesignhtml);
		return (M)this;
	}

	public java.lang.String getExpDesignhtml() {
		return get("exp_designhtml");
	}

	public M setExpBgimg(java.lang.String expBgimg) {
		set("exp_bgimg", expBgimg);
		return (M)this;
	}

	public java.lang.String getExpBgimg() {
		return get("exp_bgimg");
	}

	public M setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}

	public java.lang.Integer getIsDefault() {
		return get("is_default");
	}

	public M setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
		return (M)this;
	}

	public java.lang.Integer getPagewidth() {
		return get("pagewidth");
	}

	public M setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
		return (M)this;
	}

	public java.lang.Integer getPageheight() {
		return get("pageheight");
	}

	public M setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
		return (M)this;
	}

	public java.lang.Integer getOffsetx() {
		return get("offsetx");
	}

	public M setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
		return (M)this;
	}

	public java.lang.Integer getOffsety() {
		return get("offsety");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
