package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAgent<M extends BaseAgent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public M setAgentName(java.lang.String agentName) {
		set("agent_name", agentName);
		return (M)this;
	}

	public java.lang.String getAgentName() {
		return get("agent_name");
	}

	public M setAgentPhone(java.lang.String agentPhone) {
		set("agent_phone", agentPhone);
		return (M)this;
	}

	public java.lang.String getAgentPhone() {
		return get("agent_phone");
	}

	public M setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
		return (M)this;
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public M setAreaTreePath(java.lang.String areaTreePath) {
		set("area_tree_path", areaTreePath);
		return (M)this;
	}

	public java.lang.String getAreaTreePath() {
		return get("area_tree_path");
	}

	public M setAgentAddr(java.lang.String agentAddr) {
		set("agent_addr", agentAddr);
		return (M)this;
	}

	public java.lang.String getAgentAddr() {
		return get("agent_addr");
	}

	public M setExpireDate(java.util.Date expireDate) {
		set("expire_date", expireDate);
		return (M)this;
	}

	public java.util.Date getExpireDate() {
		return get("expire_date");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}

	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
