package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMultiGroup<M extends BaseMultiGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setOfferNum(java.lang.Integer offerNum) {
		set("offer_num", offerNum);
		return (M)this;
	}

	public java.lang.Integer getOfferNum() {
		return get("offer_num");
	}

	public M setQuota(java.lang.Integer quota) {
		set("quota", quota);
		return (M)this;
	}

	public java.lang.Integer getQuota() {
		return get("quota");
	}

	public M setValidTime(java.lang.Integer validTime) {
		set("valid_time", validTime);
		return (M)this;
	}

	public java.lang.Integer getValidTime() {
		return get("valid_time");
	}

	public M setReUnionNum(java.lang.Integer reUnionNum) {
		set("re_union_num", reUnionNum);
		return (M)this;
	}

	public java.lang.Integer getReUnionNum() {
		return get("re_union_num");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
