package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExpressComp<M extends BaseExpressComp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setExpKey(java.lang.String expKey) {
		set("exp_key", expKey);
		return (M)this;
	}

	public java.lang.String getExpKey() {
		return get("exp_key");
	}

	public M setCompanyCode(java.lang.String companyCode) {
		set("company_code", companyCode);
		return (M)this;
	}

	public java.lang.String getCompanyCode() {
		return get("company_code");
	}

	public M setExpName(java.lang.String expName) {
		set("exp_name", expName);
		return (M)this;
	}

	public java.lang.String getExpName() {
		return get("exp_name");
	}

}
